resources:
  repositories:
  - repository: OpenAstronomy
    type: github
    endpoint: glue-viz
    name: OpenAstronomy/azure-pipelines-templates
    ref: master

jobs:

- template: run-tox-env.yml@OpenAstronomy
  parameters:

    xvfb: true

    coverage: codecov

    libraries:
      apt:
        - libxcb.*-dev
        - libxkbcommon-x11-dev

    envs:

    - linux: codestyle

    - linux: py36-test
    - macos: py37-test
    - windows: py38-test
    - linux: py39-test
    - macos: py310-test
